#!/bin/bash
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="go"

ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"

cp Dockerfile "$BUILD_DIR/"
[[ $ARCH = "x86_64" ]] || {
  # TODO(hkjn): Improve this special-casing to support different CPU
  # architectures. Just call it hkjn/x86_64-alpine as well?
  sed -i "s/FROM hkjn\//FROM hkjn\/$ARCH-/" "$BUILD_DIR/Dockerfile"
  DOCKER_IMAGE="$ARCH-$DOCKER_IMAGE"
}

TAG="$DOCKER_USER/$DOCKER_IMAGE"
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
